export const fotos = [
    {
        nome: "Playstation 5",
        url: "/imagens/PlayStation5.jpg",
        descricao: "Console",
        preco: "R$4000,00",
        estoque: 2,
        nomev: "João",
        sobrenome: "Claudio",
        email: "jc@gmail.com",
        cidade: "Belo Horizonte",
        telefone: "9999998888"
    },
    {
        nome: "Air Friyer",
        url: "/imagens/FritadeiraElétrica.jpg",
        descricao: "Fritadeira Elétrica",
        preco: "R$ 250,00",
        estoque: 7,
        nomev: "João",
        sobrenome: "Claudio",
        email: "jc@gmail.com",
        cidade: "Belo Horizonte",
        telefone: "9999998888"
    },
    {
        nome: "Smart Tv",
        url: "/imagens/SamsungSmartTV50CrystalUHD.jpg",
        descricao: "Smart TV Samsung",
        preco: "R$3000,00",
        vendedor: "João",
        estoque: 4,
        nomev: "João",
        sobrenome: "Claudio",
        email: "jc@gmail.com",
        cidade: "Belo Horizonte",
        telefone: "9999998888"
    },
    {
        nome: "Moletom de otaku",
        url: "/imagens/MoletomAkatsukiNaruto.jpg",
        descricao: "Manto da Akatsuki",
        preco: "R$ sua alma",
        vendedor: "Breno",
        estoque: 1,
        nomev: "João",
        sobrenome: "Claudio",
        email: "jc@gmail.com",
        cidade: "Belo Horizonte",
        telefone: "9999998888"
    },
    {
        nome: "Nintendo Switch",
        url: "/imagens/NintendoSwitch.jpg",
        descricao: "Console",
        preco: "R$ 2600,00",
        vendedor: "José",
        estoque: 12,
        nomev: "João",
        sobrenome: "Claudio",
        email: "jc@gmail.com",
        cidade: "Belo Horizonte",
        telefone: "9999998888"
    },
]